name: default
# Tests PR-triggered workflows
on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main
      - pre-release

jobs:
  testbuild:
    name: regression-testing
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
